{% set version = "2022.11.0" %}
{% set name = "fsspec" %}

package:
  name: fsspec
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/filesystem_spec/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c0c8373aba084c192396796eb3445841627fa16c7e43fc984439ae5b1b87545

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

# fixture 'mocker' not found
{% set deselect_tests = " --deselect=fsspec/tests/test_callbacks.py::test_tqdm_callback" %}

test:
  source_files:
    - fsspec
  imports:
    - fsspec
    - fsspec.implementations
  commands:
    - pip check
    - pytest -v {{ deselect_tests }} fsspec/tests
  requires:
    - pip
    - pytest
    - requests
    - numpy
    - aiohttp !=4.0.0a0,!=4.0.0a1

about:
  description : |
    To produce a template or specification for a file-system interface, that specific implementations should follow, 
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific 
    internal implementation decisions with any given backend.
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
  skip-lints:
    - missing_doc_source_url
    - missing_license_url
