{% set version = "2022.10.0" %}
{% set name = "fsspec" %}
{% set sha256 = "cb6092474e90487a51de768170f3afa50ca8982c26150a59072b16433879ff1d" %}


package:
  name: fsspec
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  imports:
    - fsspec
    - fsspec.implementations
  commands:
    - pip check

about:
  description : |
    To produce a template or specification for a file-system interface, that specific implementations should follow, 
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific 
    internal implementation decisions with any given backend.
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  license_url: https://github.com/fsspec/filesystem_spec/blob/master/LICENSE
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io/en/latest/
  doc_source_url: https://github.com/fsspec/filesystem_spec/tree/master/docs

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
