{% set name = "fsspec" %}
{% set version = "2025.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/filesystem_spec/archive/refs/tags/{{ version }}.tar.gz
  sha256: a71eacc36f0a5cefcd8c7b0754cba1970a51e4d6c9b1a6c08ecc9ad01923acd5

build:
  number: 0
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
  run_constrained:
    - pyarrow >=1
    - aiohttp !=4.0.0a0, !=4.0.0a1

test:
  source_files:
    - fsspec
  imports:
    - fsspec
    - fsspec.implementations
    - fsspec.archive
    - fsspec.asyn
    - fsspec.caching
    - fsspec.callbacks
    - fsspec.compression
    - fsspec.config
    - fsspec.core
    - fsspec.exceptions
    - fsspec.registry
    - fsspec.spec
    - fsspec.transaction
    - fsspec.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # FAILED fsspec/tests/test_spec.py::test_posix_tests_bash_stat[test0/*.yaml-expected37] - AssertionError: assert ['‘test0/test0.yaml’'] == ['test0/test0.yaml']
    - pytest -v -k "not (test_posix_tests_bash_stat)" fsspec/tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-asyncio !=0.22.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - requests
    - numpy

about:
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  description: |
    To produce a template or specification for a file-system interface, that specific implementations should follow,
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific
    internal implementation decisions with any given backend.
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger