{% set name = "fsspec" %}
{% set version = "2025.3.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/filesystem_spec/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0388329e9130a7d936bf960d1502ff17b6defe7dacab54daa7991885cf9a2702

build:
  number: 0
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
  run_constrained:
    - pyarrow >=1
    - aiohttp !=4.0.0a0, !=4.0.0a1

test:
  source_files:
    - fsspec
  imports:
    - fsspec
    - fsspec.implementations
  commands:
    - pip check
    - pytest -v fsspec/tests -m asyncio
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-asyncio !=0.22.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - requests
    - numpy

about:
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  description : |
    To produce a template or specification for a file-system interface, that specific implementations should follow, 
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific 
    internal implementation decisions with any given backend.
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
