{% set name = "fsspec" %}
{% set version = "2025.3.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e52c77ef398680bbd6a98c0e628fbc469491282981209907bbc8aea76a04fdc6

build:
  number: 0
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
  run_constrained:
    - pyarrow >=1

test:
  imports:
    - fsspec
    - fsspec.implementations
  commands:
    - pip check

about:
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  description : |
    To produce a template or specification for a file-system interface, that specific implementations should follow, 
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific 
    internal implementation decisions with any given backend.
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
