{% set version = "2022.3.0" %}
{% set name = "fsspec" %}
{% set sha256 = "fd582cc4aa0db5968bad9317cae513450eddd08b2193c4428d9349265a995523" %}


package:
  name: fsspec
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - jinja2
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - fsspec
    - fsspec.implementations
  commands:
    - pip check || true   # [not win]
    - pip check || 1      # [win]

about:
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io
  doc_source_url: https://github.com/fsspec/filesystem_spec/tree/master/docs

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
