{% set version = "2021.10.1" %}
{% set name = "fsspec" %}
{% set sha256 = "c245626e3cb8de5cd91485840b215a385fa6f2b0f6ab87978305e99e2d842753" %}


package:
  name: fsspec
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - jinja2
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  requires:
    - pip
    - python <3.10
  imports:
    - fsspec
  commands:
    - pip check

about:
  home: https://github.com/martindurant/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/intake/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
