{% set name = "fsspec" %}
{% set version = "2024.3.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f39780e282d7d117ffb42bb96992f8a90795e4d0fb0f661a70ca39fe9c43ded9

build:
  number: 0
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - fsspec
    - fsspec.implementations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  description : |
    To produce a template or specification for a file-system interface, that specific implementations should follow, 
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific 
    internal implementation decisions with any given backend.
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
