{% set version = "0.4.5" %}
{% set name = "fsspec" %}
{% set sha256 = "824e406f5628cfde927ac945acf4ff70bc712b8bd204d7b99fe127993254db70" %}

package:
   name: fsspec
   version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - jinja2
  run:
    - python >=3.5

test:
  imports:
    - fsspec

about:
  home: https://github.com/martindurant/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "A specification for pythonic filesystems"

extra:
  recipe-maintainers:
    - martindurant
