{% set name = "fsspec" %}
{% set version = "2024.10.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eda2d8a4116d4f2429db8550f2457da57279247dd930bb12f821b58391359493

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
  run_constrained:
    - pyarrow >=1

test:
  imports:
    - fsspec
    - fsspec.implementations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/fsspec/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  description : |
    To produce a template or specification for a file-system interface, that specific implementations should follow, 
    so that applications making use of them can rely on a common behaviour and not have to worry about the specific 
    internal implementation decisions with any given backend.
  dev_url: https://github.com/fsspec/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
