{% set version = "2021.8.1" %}
{% set name = "fsspec" %}
{% set sha256 = "af125917788b77782899bbd4484d29e5407f53d2bb04cdfa025fe4931201a555" %}

package:
  name: fsspec
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jinja2
  run:
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - fsspec
  commands:
    - pip check

about:
  home: https://github.com/martindurant/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/intake/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
