{% set version = "2022.1.0" %}
{% set name = "fsspec" %}
{% set sha256 = "0bdd519bbf4d8c9a1d893a50b5ebacc89acd0e1fe0045d2f7b0e0c1af5990edc" %}


package:
  name: fsspec
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - jinja2
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  requires:
    - pip
    - python <3.10
  imports:
    - fsspec
    - fsspec.implementations
  commands:
    - pip check

about:
  home: https://github.com/martindurant/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/intake/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
