travis:
  secure:
    BINSTAR_TOKEN: di6ih9BgbUVzniEMB/6WqgoYDV4pOCCopXBEe9jgNnb555uJhL938th4C3etnHA1QCMv1E+U28yfsAEueYU3cGAaI1BrFHoycDSQqa4kFV0iLbUeMDtecPoKvV1xxcuCLLjf6549JkT8a8dVbaSU71vSQ93niqCzgsB+IA9Y9414vYfvbiwv9ETTYYWroLZYFJ+n74Gf35eyCxKjwSlSiGGraDD8A2bRxIhLcb+IfWYGhQ/S4i5ssa4NJgG5jPB9zJf7qwtmJkZ+sfCAbSX4PAkoJhXnmSHoIoSmcpFfaTUEWTfKk/VfUkTTeyvdrP9ZPj4pmOEWaXl7qUuff2qifK1riExUs6IySsaLne7sirRtIOCYXoR0rPoO7SkbeHki0TAq6inPPlhGGdhZPJwtgHNfWHt387otDrPiw71L1alo0NDdCYSTXQUUTeHhMoDhJGr+gb6UjNY5fmucmnvW/1hdH/FkNLLUefMB8qO6IBNDqUDzxOKYUsqkQWKXDcPioev2HSdQGWyxUHvToB28f6qBMMhM9IE6eytQAtGs7tZQNzxuGqg9PUvDPirZkIV1tZ5XP7kulemPGLiJhmbwW2NKbZUqts9otHKXpXDv2xUcUEys4SFS3vNDCqF0au2slM7YeczsUGFlnKMby0j7lplpqBSsCWqCPSC5qCL1dao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
